dist: trusty
language: csharp
mono: none
dotnet: 2.1.403

before_script:
- "ls -lhaF"

script:
- "dotnet restore"
- "dotnet build /p:CiBuildId=$TRAVIS_BUILD_NUMBER"
- "dotnet test AdventOfCode2018.Tests --no-build"
